# Generated by Django 4.2.7 on 2023-11-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitRegistry', '0003_alter_visit_date_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visits',
            new_name='Visit',
        ),
    ]
