# Generated by Django 4.2.7 on 2023-11-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitRegistry', '0008_rename_is_confirmed_visit_confirmed_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='confirmed_patient',
            new_name='booked_by_patient',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='confirmed_therapist',
            new_name='is_confirmed',
        ),
    ]
