# Generated by Django 4.2.7 on 2023-11-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitRegistry', '0010_visit_date_is_occupied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit_date',
            old_name='is_occupied',
            new_name='is_reserved',
        ),
        migrations.AddField(
            model_name='visit_date',
            name='is_visit',
            field=models.BooleanField(default=False),
        ),
    ]
