# Generated by Django 4.2.7 on 2023-12-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitRegistry', '0012_alter_therapist_visit_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visit_date',
            new_name='VisitDate',
        ),
    ]
